### ISSUE TITLE
Set indicator position

### ISSUE THREAD

**Issue by ycensi** [abbasmoosavi/react-native-best-viewpager#10]
Is there a way to change the position of the page indicator? I need to put it before ViewPager, but I can't find a prop for that.

**Comment by RiatIO** [comment]
I'm not quite sure what you want to achieve. But would for instance it be possible to add a reference to the ViewPager: 
```
const viewPager = useRef();

<ViewPager ref={viewPager} ... />
```

and then proceed to call: 

`viewPager.current.setPage(POSITION)`

Or am I interpreting the question incorrectly?

**Comment by ngoclt** [comment]
> Is there a way to change the position of the page indicator? I need to put it before ViewPager, but I can't find a prop for that.

Use Flexbox to put it on the top. 

Use this style for your `<IndicatorViewPager style={styles.pager}`>

```css
  pager: {
    flex: 1,
    alignItems: 'stretch',
    flexDirection: 'column-reverse',
  },
```
